CREATE TABLE [dbo].[STATE_DATA](
	[STATE_CODE] [varchar](50) NOT NULL,
	[STATE_NAME] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[STATE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


